SRC_DIRS ?= ../c_project/src ../c_project/src/nested_src
INC_DIRS ?= ../c_project/inc ../c_project/inc/nested_inc

TEST_SRC_DIRS ?= .
TEST_INC_DIRS ?=

TEST_FRAMEWORK_SRC_DIRS ?= ../../test/framework/unity/src ../../test/framework/fff
TEST_FRAMEWORK_INC_DIRS ?= ../../test/framework/unity/src ../../test/framework/fff

include ../../cottimake.mk